[package]
name = "timestitch"
version = "0.2.3"
authors = ["Skylor R Schermer <skyschermer@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/solarretrace/timestitch-rs"
description = "A journalling and timeline formatting tool"
readme = "readme.md"
keywords = ["journal"]
categories = ["command-line-utilities"]
homepage = "https://github.com/solarretrace/timestitch-rs"
exclude = [
	"*.sublime-project",
	"*.sublime-workspace",
	".kateproject",
]

[lib]
name = "timestitch"

[features]
default = []

# Required dependencies
[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.6", features = ["derive", "suggestions", "color", "cargo"] }
colored = "3.1"
either = "1.17.0"
regex = "1.13"
ron = "0.12"
rustc_version_runtime = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1"
tracing = { version = "0.1.31" }
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
table-gen = { version = "*", path = "../table-gen-rs/table-gen" }
table-gen-markdown = { version = "*", path = "../table-gen-rs/table-gen-markdown" }


# The development profile, used for `cargo build`
[profile.dev]
opt-level = 0
debug = false

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = true

