////////////////////////////////////////////////////////////////////////////////
// Timestitch journal and timeline creator
////////////////////////////////////////////////////////////////////////////////
// This code is dual licensed using the MIT or Apache 2 license.
// See license-mit.md and license-apache.md for details.
////////////////////////////////////////////////////////////////////////////////
//! Values representing time periods within the measuring range of a standard
//! 24-hour clock.
//! 
//! The time topology is generated by hours, minutes, or seconds. Higher or
//! lower resolution timescales are not supported.
////////////////////////////////////////////////////////////////////////////////

// Internal library imports.
use crate::Calendar;
use crate::error::CaptureGroupCountError;
use crate::util::CapturesMap;

// External library imports.
use serde::Deserialize;
use serde::Serialize;
use regex::Regex;

// Standard library imports.
use std::cmp::Ordering;
use std::collections::HashMap;
use std::num::ParseIntError;
use std::sync::OnceLock;


////////////////////////////////////////////////////////////////////////////////
// TimeFormat
////////////////////////////////////////////////////////////////////////////////
/// The time format.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(Deserialize, Serialize)]
pub enum TimeFormat {
	/// The 12-hour time format.
	Hours12,
	/// The 24-hour time format.
	Hours24,
}

impl TimeFormat {
	/// Returns a ClockTimeParseError if the given hour value lies outside of
	/// the valid range for the format.
	fn validate_hour(self, hour: u8) -> Result<u8, ClockTimeParseError> {
		match self {
			TimeFormat::Hours12 if hour >= 12 => {
				Err(ClockTimeParseError::InvalidClockTime)
			},
			TimeFormat::Hours24 if hour >= 24 => {
				Err(ClockTimeParseError::InvalidClockTime)
			},
			_ => Ok(hour)
		}
	}
}

impl std::fmt::Display for TimeFormat {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			TimeFormat::Hours12 => write!(f, "12-hour"),
			TimeFormat::Hours24 => write!(f, "24-hour"),
		}
	}
}


////////////////////////////////////////////////////////////////////////////////
// ClockTime
////////////////////////////////////////////////////////////////////////////////
/// A time period resolvable to units of an hour, minute, or second.
#[derive(Debug, Clone, Copy)]
#[derive(Deserialize, Serialize)]
pub struct ClockTime {
	/// The hour.
	hour: u8,
	/// The minute.
	minute: Option<u8>,
	/// The second.
	second: Option<u8>,
}

impl ClockTime {
	/// The time period of the first second of a day.
	pub const MIN: Self = Self { hour: 0, minute: Some(0), second: Some(0) };

	/// The time period of at last second of a day.
	pub const MAX: Self = Self { hour: 23, minute: Some(59), second: Some(59) };

	/// Constructs a new `ClockTime` from the given hour value.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn from_h(hour: u8) -> Self  {
		assert!(hour < 24);
		Self {
			hour,
			minute: None,
			second: None,
		}
	}

	/// Constructs a new `ClockTime` from the given hour & minute values.
	///
	/// # Panics
	///
	/// Panics if any values are outside of the valid ranges.
	#[must_use]
	pub fn from_hm(hour: u8, minute: u8) -> Self  {
		assert!(hour < 24);
		assert!(minute < 60);
		Self {
			hour,
			minute: Some(minute),
			second: None,
		}
	}

	/// Constructs a new `ClockTime` from the given hour, minute, and second
	/// values.
	///
	/// # Panics
	///
	/// Panics if any values are outside of the valid ranges.
	#[must_use]
	pub fn from_hms(hour: u8, minute: u8, second: u8) -> Self  {
		assert!(hour < 24);
		assert!(minute < 60);
		assert!(second < 60);
		Self {
			hour,
			minute: Some(minute),
			second: Some(second),
		}
	}

	/// Constructs a new `ClockTime` from the given hour, minute, and second
	/// values.
	///
	/// If the seconds is provided without a minute, or a minute without an
	/// hour, a value of `0` will be assumed for the less specific values.
	///
	/// # Panics
	///
	/// Panics if any values are outside of the valid ranges.
	#[must_use]
	pub fn from_hms_opt(
		hour: Option<u8>,
		minute: Option<u8>,
		second: Option<u8>)
		-> Option<Self>
	{
		if let Some(hour) = hour {
			assert!(hour < 24);
		}
		
		let hour = if let Some(minute) = minute {
			assert!(minute < 60);
			hour.or(Some(0))
		} else {
			None
		};
		
		let (hour, minute) = if let Some(second) = second {
			assert!(second < 60);
			(hour.or(Some(0)), minute.or(Some(0)))
		} else {
			(None, None)
		};

		hour.map(|hour| Self {
			hour,
			minute,
			second,
		})
	}

	/// Sets the hour and returns the `ClockTime`.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn with_hour(mut self, hour: u8) -> Self {
		assert!(hour < 24);
		self.hour = hour;
		self
	}

	/// Sets the minute and returns the `ClockTime`.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn with_minute_opt(mut self, minute: Option<u8>) -> Self {
		if let Some(m) = minute { assert!(m < 60); }
		self.minute = minute;
		self
	}

	/// Sets the minute and returns the `ClockTime`.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn with_minute(mut self, minute: u8) -> Self {
		assert!(minute < 60);
		self.minute = Some(minute);
		self
	}

	/// Sets the second and returns the `ClockTime`.
	///
	/// If the minute has not been set, it will be set to `0`.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn with_second_opt(mut self, second: Option<u8>) -> Self {
		if let Some(s) = second { assert!(s < 60); }
		self.second = second;
		self.minute = self.minute.or(Some(0));
		self

	}

	/// Sets the second and returns the `ClockTime`.
	///
	/// If the minute has not been set, it will be set to `0`.
	///
	/// # Panics
	///
	/// Panics if the value is outside of the valid range.
	#[must_use]
	pub fn with_second(mut self, second: u8) -> Self {
		assert!(second < 60);
		self.second = Some(second);
		self.minute = self.minute.or(Some(0));
		self
	}

	/// Sets the values for any missing components to those of the provided
	/// value and returns the `ClockTime`.
	///
	/// If the second value is provided without a minute set, the minute will
	/// be set to `0`.
	#[must_use]
	pub fn extend(mut self, time: ClockTime) -> Self {
		if self.minute.is_none() {
			self.minute = time.minute;
		}
		if self.second.is_none() {
			self.second = time.second;
			self.minute = self.minute.or(Some(0));
		}
		self
	}

	/// The hour.
	///
	/// Values range from 0 to 23.
	pub fn hour(&self) -> u8 {
		self.hour
	}

	/// The minute.
	///
	/// Values range from 0 to 59.
	pub fn minute(&self) -> Option<u8> {
		self.minute
	}

	/// The second.
	///
	/// Values range from 0 to 59.
	pub fn second(&self) -> Option<u8> {
		self.second
	}

}

impl std::fmt::Display for ClockTime {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Self { hour, minute: None, second: None }
				=> write!(f, "{:02}", hour),
			Self { hour, minute: Some(m), second: None }
				=> write!(f, "{:02}:{:02}", hour, m),
			Self { hour, minute: Some(m), second: Some(s) }
				=> write!(f, "{:02}:{:02}:{:02}", hour, m, s),
			Self { hour, minute: None, second: Some(s) }
				=> write!(f, "{:02}:00:{:02}", hour, s),
		}
	}
}


impl Ord for ClockTime {
	fn cmp(&self, other: &Self) -> Ordering {
		self.hour.cmp(&other.hour)
			.then_with(|| match (self.minute, other.minute) {
				(Some(a), Some(b)) => a.cmp(&b),
				(None,    Some(_)) => Ordering::Greater,
				(Some(_), None)    => Ordering::Less,
				(None,    None)    => Ordering::Equal,
			})
			.then_with(|| match (self.second, other.second) {
				(Some(a), Some(b)) => a.cmp(&b),
				(None,    Some(_)) => Ordering::Greater,
				(Some(_), None)    => Ordering::Less,
				(None,    None)    => Ordering::Equal,
			})
	}
}


impl PartialOrd for ClockTime {
	fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
		Some(self.cmp(other))
	}
}

impl PartialEq for ClockTime {
	fn eq(&self, other: &Self) -> bool {
		self.cmp(other).is_eq()
	}
}

impl Eq for ClockTime {}


impl Calendar for ClockTime {
	type FormatReq = TimeFormat;
	type ParseErr = ClockTimeParseError;

	fn parse_format(
		text: &str,
		format: &Self::FormatReq,
		re: &Regex,
		capture_map: &HashMap<usize, usize>)
		-> Result<Self, Self::ParseErr> 
	{
		let cap = CapturesMap::new(re
			.captures(&text)
			.ok_or_else(|| ClockTimeParseError::CaptureMatchFailure(
				text.to_owned().into_boxed_str()))?,
			&capture_map);
		
		let hour = cap.get(1).map(|g| g.as_str().parse::<u8>()).transpose()?
			.ok_or(ClockTimeParseError::InvalidClockTime)?;
		let hour = format.validate_hour(hour)?;
		let minute = cap.get(2).map(|g| g.as_str().parse::<u8>()).transpose()?;
		if minute.is_some_and(|s| s >= 60) {
			return Err(ClockTimeParseError::InvalidClockTime);
		}
		let second = cap.get(3).map(|g| g.as_str().parse::<u8>()).transpose()?;
		if second.is_some_and(|s| s >= 60) {
			return Err(ClockTimeParseError::InvalidClockTime);
		}
		Ok(Self { hour, minute, second })
	}

	fn earliest(&self) -> Self {
		self.extend(Self::MIN)
	}

	fn latest(&self) -> Self {
		self.extend(Self::MAX)
	}
}


////////////////////////////////////////////////////////////////////////////////
// Errors
////////////////////////////////////////////////////////////////////////////////
#[derive(Debug, Clone)]
pub enum ClockTimeParseError {
	InvalidClockTime,
	CaptureMatchFailure(Box<str>),
	CaptureGroupCountError(CaptureGroupCountError<TimeFormat>),
	ParseIntError(ParseIntError),
}

impl From<ParseIntError> for ClockTimeParseError {
	fn from(e: ParseIntError) -> Self {
		ClockTimeParseError::ParseIntError(e)
	}
}

impl std::fmt::Display for ClockTimeParseError {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		todo!()
	}
}

impl std::error::Error for ClockTimeParseError {}


////////////////////////////////////////////////////////////////////////////////
// Tests
////////////////////////////////////////////////////////////////////////////////
#[cfg(test)]
mod test {
	use super::*;
	use std::assert_matches;

	#[test]
	fn order_h() {
		let a = ClockTime::from_h(4);
		let b = ClockTime::from_h(7);
		assert!(a < b);
	}

	#[test]
	fn order_hm() {
		let a = ClockTime::from_hm(4, 15);
		let b = ClockTime::from_hm(4, 16);
		assert!(a < b);
	}

	#[test]
	fn order_hms() {
		let a = ClockTime::from_hms(4, 16, 59);
		let b = ClockTime::from_hms(4, 16, 45);
		assert!(a > b);
	}

	#[test]
	fn parse_h() {
		let a = ClockTime::from_str("9")
			.expect("parse clock time");
		assert_eq!(a, ClockTime::from_h(9));

		let a = ClockTime::from_str("02")
			.expect("parse clock time");
		assert_eq!(a, ClockTime::from_h(2));

		let a = ClockTime::from_str("23")
			.expect("parse clock time");
		assert_eq!(a, ClockTime::from_h(23));
	}

	#[test]
	fn parse_invalid_h() {
		let a = ClockTime::from_str("25");
		assert_matches!(a, Err(ClockTimeParseError::InvalidClockTime));
	}

	#[test]
	fn parse_hm() {
		let a = ClockTime::from_str("02:10")
			.expect("parse clock time");
		assert_eq!(a, ClockTime::from_hm(2, 10));
	}

	#[test]
	fn parse_invalid_hm() {
		let a = ClockTime::from_str("02:60");
		assert_matches!(a, Err(ClockTimeParseError::InvalidClockTime));

		let a = ClockTime::from_str("52:02");
		assert_matches!(a, Err(ClockTimeParseError::InvalidClockTime));
	}

	#[test]
	fn parse_hms() {
		let a = ClockTime::from_str("02:10:59")
			.expect("parse clock time");
		assert_eq!(a, ClockTime::from_hms(2, 10, 59));
	}

	#[test]
	fn parse_invalid_hms() {
		let a = ClockTime::from_str("02:40:60");
		assert_matches!(a, Err(ClockTimeParseError::InvalidClockTime));

		let a = ClockTime::from_str("2:02:99");
		assert_matches!(a, Err(ClockTimeParseError::InvalidClockTime));
	}
}
